### ISSUE TITLE
Problems with test connection

### ISSUE THREAD

**Issue by zuttrax** [Ingenico-ePayments/connect-sdk-go#4]
I have been having troubles with the function to test connection, always I receive the error with code 9002, and when I test with the SDK for node js this works

![image](https://user-images.githubusercontent.com/12839652/201677015-12471627-9112-47b6-ba5f-28aaa2860200.png)

response

![image](https://user-images.githubusercontent.com/12839652/201677097-390763e4-5b58-484b-8a45-95adac66b76f.png)

**Comment by rob-spoor** [comment]
When you use `connectsdk.CreateClient`, the default configuration will be used: [CommunicatorConfiguration.go#L63](https://github.com/Ingenico-ePayments/connect-sdk-go/blob/master/configuration/CommunicatorConfiguration.go#L63). This includes a hard-coded URL: https://world.api-ingenico.com. Is this the same URL you're using in the Node.js SDK?

If not, you'll need to create a `configuration.CommunicatorConfiguration` instance in combination with `connectsdk.CreateClientFromConfiguration`. This is explained at [Initialization of the Go SDK](https://epayments.developer-ingenico.com/documentation/sdk/server/go/#initialization), subsection "Using CommunicatorConfiguration". That uses TOML to set the configuration, but you can also just set the configuration properties directly:

```go
conf, err := connectsdk.CreateConfiguration(apiKeyID, secretAPIKey, "Ingenico");
// omitted: error handling

// for another https URL:
conf.APIEndpoint.Host = "<other host>"
// or to overwrite the URL completely:
//conf.APIEndpoint = URL{ ... }

return connectsdk.CreateClientFromConfiguration(conf)
```
